#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi

done

ifconfig eth0 10.0.0.200 netmask 255.255.252.0
route add default gw 10.0.1.1

telnetd&

cd /etc/init.d/
./run



#cd /box/
#chmod 777 ./load
#./load
